name: Install npm packages

on:
  repository_dispatch: 
    types: [clone]

jobs:
  install_packages:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World by LGM
      uses: lgmorand/github-action-hello@v2


