name: Create Branch

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check for "done" in commit message
      run: |
        if grep -q "done" <<< "$GITHUB_EVENT_NAME"; then
          branch_name=`echo $GITHUB_EVENT_NAME | awk '{print $2}' | cut -d '"' -f2`
          git branch $branch_name
          git push -u origin $branch_name
        fi
