on:
  push:
    branches:
      - '**'

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Commit Message
        run: |
          message=$(git log -1 --pretty=%B)
          echo "Commit message: $message"
      - name: Check if commit message includes "done"
        run: |
          if [[ $message == *"done"* ]]; then
            echo "Commit message includes 'done'"
          else
            echo "Commit message does not include 'done'"
            exit 1
          fi
      - name: Discord Notification
        uses: fateyan/action-discord-notifier@v1
        if: success()
        with:
          message-title: New Commits Pushed
          webhook: https://discordapp.com/api/webhooks/1064901964070141963/81q8rcsOIwOWhpxVamBVlVj9h_6ZoxpwRFQPVNN2-BsEv6AxSDm6Y7yd6pQlNUnpmxV_

