name: Install npm packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install npm packages
      run: npm ci

